# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

project 'Alarm_AutoSet.xcodeproj'
platform :ios, '9.0'
target 'Alarm_AutoSet' do
  # Fixes required for pod specs to work with rn 0.42
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'	

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
#  pod 'react-native-maps', path: '../../'
#  pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS
# Add new pods below this line
# pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

pod 'RNIap', :path => '../node_modules/react-native-iap'

pod 'RNFS', :path => '../node_modules/react-native-fs'

pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'


# pod 'lottie-ios', :path => '../node_modules/lottie-ios'
# pod 'AppLovinSDK'
pod 'GoogleMobileAdsMediationAppLovin'
pod 'GoogleMobileAdsMediationInMobi'
pod 'Google-Mobile-Ads-SDK'

end



post_install do |installer|
    installer.pods_project.targets.each do |target|

        # The following is needed to ensure the "archive" step works in XCode.
        # It removes React & Yoga from the Pods project, as it is already included in the main project.
        # Without this, you'd see errors when you archive like:
        # "Multiple commands produce ... libReact.a"
        # "Multiple commands produce ... libyoga.a"

        targets_to_ignore = %w(React yoga)

        if targets_to_ignore.include? target.name
            target.remove_from_project
        end

    end
end
